services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase
      NODE_ENV: development
      WATCHPACK_POLLING: true
    depends_on:
      - db

volumes:
  db_data: