services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

  rag_db:
    image: pgvector/pgvector:pg17
    restart: always
    environment:
      POSTGRES_USER: raguser
      POSTGRES_PASSWORD: ragpassword
      POSTGRES_DB: ragdatabase
      PGPORT: 5433
    ports:
      - "5433:5433"
    volumes:
      - rag_db_data:/var/lib/postgresql/data

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase
      NODE_ENV: development
      WATCHPACK_POLLING: true
      RAG_URI: http://backend:8000/chat_request
      IMG_URI: http://backend:8000/img
    depends_on:
      db:
        condition: service_healthy

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      
      PYTHONUNBUFFERED: 1
      DATABASE_URL: postgresql://raguser:ragpassword@rag_db:5432/ragdatabase
      DB_VECTOR_EXTENSION: pgvector
      OPENROUTER_API_KEY: 67
      LLM_URL: https://openrouter.ai/api/v1
      LLM_NAME: inclusionai/ling-2.6-flash:free
    depends_on:
      - rag_db

volumes:
  db_data:
  rag_db_data: